version: '3.8'
services:
  database:
    image: postgres:17
    container_name: proga
    environment:
      POSTGRES_USER: alexa
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: proga
    ports:
      - "6969:5432"
    volumes:
      - ./01-init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - proga_data:/var/lib/postgresql/data
volumes:
  proga_data:
